/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List threads */
        get: operations["threads.list"];
        put?: never;
        /** Create thread */
        post: operations["threads.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/threads/{threadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get thread */
        get: operations["threads.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename thread */
        patch: operations["threads.rename"];
        trace?: never;
    };
    "/api/v1/threads/{threadId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive thread */
        post: operations["threads.archive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/threads/{threadId}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unarchive thread */
        post: operations["threads.unarchive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/threads/{threadId}/regenerate-title": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate thread title */
        post: operations["threads.regenerateTitle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/threads/{threadId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tasks */
        get: operations["tasks.list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get task */
        get: operations["tasks.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{taskId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List task messages */
        get: operations["tasks.messages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/threads/{threadId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List thread messages */
        get: operations["messages.list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/threads/{threadId}/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send message */
        post: operations["messages.send"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/threads/{threadId}/interrupt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Interrupt thread */
        post: operations["messages.interrupt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/threads/{threadId}/messages/{eventId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel queued message */
        post: operations["messages.cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/threads/{threadId}/messages/{eventId}/send-now": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send queued message now */
        post: operations["messages.sendNow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/review-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get review settings */
        get: operations["reviews.settings"];
        /** Configure review settings */
        put: operations["reviews.configure"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/review-billing-transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get review billing transfer */
        get: operations["reviews.billingTransfer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/review-billing-transfer/offer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Offer review billing transfer */
        post: operations["reviews.offerBillingTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/review-billing-transfer/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept review billing transfer */
        post: operations["reviews.acceptBillingTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/review-billing-transfer/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel review billing transfer */
        post: operations["reviews.cancelBillingTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/review-billing-transfer/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decline review billing transfer */
        post: operations["reviews.declineBillingTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start review */
        post: operations["reviews.start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get usage report */
        get: operations["usage.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UsageTotals: {
            llmCredits: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
            imageCredits: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
            vmCredits: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
            totalCredits: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
        };
        Thread: {
            id: string;
            projectId: string | null;
            title: string | null;
            titleCustom: boolean;
            /** @enum {string} */
            status: "active" | "waiting" | "pending_user" | "error" | "ready_for_review" | "idle" | "archived";
            archived: boolean;
            lastModelId: string | null;
            usage: components["schemas"]["UsageTotals"];
            createdAt: string;
            updatedAt: string;
            lastActivityAt: string | null;
        };
        ThreadPage: {
            items: components["schemas"]["Thread"][];
            cursor: (string & unknown) | null;
        };
        capy_ProjectNotFound: {
            /** @enum {string} */
            _tag: "capy/ProjectNotFound";
            projectId: string;
        };
        capy_Unauthorized: {
            /** @enum {string} */
            _tag: "capy/Unauthorized";
        };
        capy_ThreadNotFound: {
            /** @enum {string} */
            _tag: "capy/ThreadNotFound";
            threadId: string;
        };
        CreateThreadRequest: {
            requestId: string & (unknown & unknown);
            projectId: string;
            title?: string;
            message: string;
            model?: {
                modelId: string;
                /** @enum {string} */
                reasoningMode?: "none" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max";
                modes?: {
                    fast?: boolean;
                    pro?: boolean;
                };
            };
            /** @enum {string} */
            machineSize?: "small" | "medium" | "large" | "ultra" | "hyper" | "bigguy";
        };
        capy_PaidFeatureUnavailable: {
            /** @enum {string} */
            _tag: "capy/PaidFeatureUnavailable";
            /** @enum {string} */
            feature: "bigguy";
        };
        capy_BillingAuthorityUnavailable: {
            /** @enum {string} */
            _tag: "capy/BillingAuthorityUnavailable";
        };
        RenameThreadRequest: {
            title: string | null;
        };
        Task: {
            id: string;
            threadId: string;
            parentId: string;
            taskPath: string;
            projectId: string | null;
            title: string | null;
            /** @enum {string} */
            status: "working" | "waiting" | "idle" | "done" | "failed";
            usage: components["schemas"]["UsageTotals"];
            createdAt: string;
            updatedAt: string;
            lastActivityAt: string | null;
        };
        TaskPage: {
            items: components["schemas"]["Task"][];
            cursor: string | null;
        };
        capy_TaskNotFound: {
            /** @enum {string} */
            _tag: "capy/TaskNotFound";
            taskId: string;
        };
        Message: {
            id: string;
            /** @enum {string} */
            source: "user" | "assistant" | "tool";
            tool?: string;
            text: string;
            authorName?: string;
            model?: string;
            attachments?: {
                file: {
                    fileId: string;
                    name: string;
                    mediaType: string;
                    sizeBytes: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                    preview?: boolean;
                    width?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                    height?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                };
                title?: string;
            }[];
            createdAt: string;
        };
        MessagePage: {
            items: components["schemas"]["Message"][];
            cursor: (string & (unknown & unknown)) | null;
        };
        SendMessageRequest: {
            text: string;
            model?: {
                modelId: string;
                /** @enum {string} */
                reasoningMode?: "none" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max";
                modes?: {
                    fast?: boolean;
                    pro?: boolean;
                };
            };
            /** @enum {string} */
            delivery?: "queue" | "steer" | "interrupt";
        };
        AdmitReceipt: {
            id: string & (unknown & unknown);
            deduped: boolean;
        };
        CancelMessageOutcome: {
            /** @enum {string} */
            outcome: "cancelled" | "tooLate";
        };
        SendNowOutcome: {
            /** @enum {string} */
            outcome: "sent" | "tooLate";
            id?: string & (unknown & unknown);
        };
        ReviewSettings: {
            repo: string;
            billingOrgId: string | null;
            heldByCaller: boolean;
            /** @enum {string} */
            autoReview: "off" | "once" | "always";
            /** @enum {string} */
            postingThreshold: "low" | "medium" | "high";
            postInvestigate: boolean;
            postNotes: boolean;
        };
        capy_ReviewRefused: {
            /** @enum {string} */
            _tag: "capy/ReviewRefused";
            reason: string;
        };
        ConfigureReviewRequest: {
            repo: string;
            /** @enum {string} */
            autoReview?: "off" | "once" | "always";
            /** @enum {string} */
            postingThreshold?: "low" | "medium" | "high";
            postInvestigate?: boolean;
            postNotes?: boolean;
        };
        capy_Forbidden: {
            /** @enum {string} */
            _tag: "capy/Forbidden";
        };
        ReviewBillingTransferOffer: {
            fromOrgId: string;
            toOrgId: string;
            createdAt: string;
        };
        ReviewBillingTransferState: {
            repo: string;
            billingOrgId: string | null;
            offer: components["schemas"]["ReviewBillingTransferOffer"] | null;
        };
        OfferReviewBillingTransferRequest: {
            repo: string;
            targetOrgId: string;
        };
        ReviewBillingTransferRequest: {
            repo: string;
        };
        StartReviewRequest: {
            repo: string;
            prNumber: number;
            idempotencyKey?: string & (unknown & unknown);
            forceRefresh?: boolean;
            sourceThreadId?: string;
            model?: string;
            /** @enum {string} */
            effort?: "none" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max";
        };
        ReviewStarted: {
            reviewId: string;
            requestId: string;
            threadId: string;
            headSha: string;
            adopted: boolean;
            sourceRecorded?: boolean;
        };
        UsageDollars: {
            llmDollars: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
            imageDollars: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
            vmDollars: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
            totalDollars: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
        };
        UsageTokenTotals: {
            inputTokens: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
            outputTokens: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
            cacheReadTokens: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
            cacheWriteTokens: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
        };
        UsageMemberDollars: {
            principalUserId: string | null;
            llmDollars: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
            imageDollars: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
            vmDollars: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
            totalDollars: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
        };
        UsageModelDollars: {
            model: string;
            label: string;
            dollars: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
            unbilled: boolean;
            tokens: components["schemas"]["UsageTokenTotals"];
        };
        UsageImageDollars: {
            endpoint: string;
            label: string;
            dollars: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
        };
        UsageReport: {
            from: string;
            to: string;
            totals: components["schemas"]["UsageDollars"];
            tokens: components["schemas"]["UsageTokenTotals"];
            members: components["schemas"]["UsageMemberDollars"][];
            models: components["schemas"]["UsageModelDollars"][];
            images: components["schemas"]["UsageImageDollars"][];
        };
        capy_InvalidRequest: {
            /** @enum {string} */
            _tag: "capy/InvalidRequest";
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "threads.list": {
        parameters: {
            query: {
                projectId: string;
                status?: "active" | "waiting" | "pending_user" | "error" | "ready_for_review" | "idle";
                limit?: number;
                cursor?: string & unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ThreadPage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadPage"];
                };
            };
            /** @description capy/Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Unauthorized"];
                };
            };
            /** @description capy/ProjectNotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_ProjectNotFound"];
                };
            };
        };
    };
    "threads.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateThreadRequest"];
            };
        };
        responses: {
            /** @description Thread */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"];
                };
            };
            /** @description capy/Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Unauthorized"];
                };
            };
            /** @description capy/PaidFeatureUnavailable */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_PaidFeatureUnavailable"];
                };
            };
            /** @description capy/ProjectNotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_ProjectNotFound"];
                };
            };
            /** @description capy/BillingAuthorityUnavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_BillingAuthorityUnavailable"];
                };
            };
        };
    };
    "threads.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thread */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"];
                };
            };
            /** @description capy/Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Unauthorized"];
                };
            };
            /** @description capy/ThreadNotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_ThreadNotFound"];
                };
            };
        };
    };
    "threads.rename": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameThreadRequest"];
            };
        };
        responses: {
            /** @description Thread */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"];
                };
            };
            /** @description capy/Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Unauthorized"];
                };
            };
            /** @description capy/ThreadNotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_ThreadNotFound"];
                };
            };
        };
    };
    "threads.archive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thread */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"];
                };
            };
            /** @description capy/Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Unauthorized"];
                };
            };
            /** @description capy/ThreadNotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_ThreadNotFound"];
                };
            };
        };
    };
    "threads.unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thread */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"];
                };
            };
            /** @description capy/Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Unauthorized"];
                };
            };
            /** @description capy/ThreadNotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_ThreadNotFound"];
                };
            };
        };
    };
    "threads.regenerateTitle": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thread */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"];
                };
            };
            /** @description capy/Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Unauthorized"];
                };
            };
            /** @description capy/ThreadNotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_ThreadNotFound"];
                };
            };
        };
    };
    "tasks.list": {
        parameters: {
            query?: {
                after?: string;
                limit?: number;
            };
            header?: never;
            path: {
                threadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TaskPage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskPage"];
                };
            };
            /** @description capy/Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Unauthorized"];
                };
            };
            /** @description capy/ThreadNotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_ThreadNotFound"];
                };
            };
        };
    };
    "tasks.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description capy/Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Unauthorized"];
                };
            };
            /** @description capy/TaskNotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_TaskNotFound"];
                };
            };
        };
    };
    "tasks.messages": {
        parameters: {
            query?: {
                after?: string & (unknown & unknown);
                limit?: number;
            };
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description MessagePage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            /** @description capy/Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Unauthorized"];
                };
            };
            /** @description capy/TaskNotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_TaskNotFound"];
                };
            };
        };
    };
    "messages.list": {
        parameters: {
            query?: {
                after?: string & (unknown & unknown);
                limit?: number;
            };
            header?: never;
            path: {
                threadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description MessagePage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            /** @description capy/Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Unauthorized"];
                };
            };
            /** @description capy/ThreadNotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_ThreadNotFound"];
                };
            };
        };
    };
    "messages.send": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description AdmitReceipt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdmitReceipt"];
                };
            };
            /** @description capy/Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Unauthorized"];
                };
            };
            /** @description capy/ThreadNotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_ThreadNotFound"];
                };
            };
        };
    };
    "messages.interrupt": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AdmitReceipt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdmitReceipt"];
                };
            };
            /** @description capy/Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Unauthorized"];
                };
            };
            /** @description capy/ThreadNotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_ThreadNotFound"];
                };
            };
        };
    };
    "messages.cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: string;
                eventId: string & (unknown & unknown);
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CancelMessageOutcome */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelMessageOutcome"];
                };
            };
            /** @description capy/Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Unauthorized"];
                };
            };
            /** @description capy/ThreadNotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_ThreadNotFound"];
                };
            };
        };
    };
    "messages.sendNow": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: string;
                eventId: string & (unknown & unknown);
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SendNowOutcome */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendNowOutcome"];
                };
            };
            /** @description capy/Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Unauthorized"];
                };
            };
            /** @description capy/ThreadNotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_ThreadNotFound"];
                };
            };
        };
    };
    "reviews.settings": {
        parameters: {
            query: {
                repo: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ReviewSettings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSettings"];
                };
            };
            /** @description capy/Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Unauthorized"];
                };
            };
            /** @description capy/ReviewRefused */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_ReviewRefused"];
                };
            };
        };
    };
    "reviews.configure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigureReviewRequest"];
            };
        };
        responses: {
            /** @description ReviewSettings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSettings"];
                };
            };
            /** @description capy/Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Unauthorized"];
                };
            };
            /** @description capy/Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Forbidden"];
                };
            };
            /** @description capy/ReviewRefused */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_ReviewRefused"];
                };
            };
        };
    };
    "reviews.billingTransfer": {
        parameters: {
            query: {
                repo: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ReviewBillingTransferState */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewBillingTransferState"];
                };
            };
            /** @description capy/Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Unauthorized"];
                };
            };
            /** @description capy/ReviewRefused */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_ReviewRefused"];
                };
            };
        };
    };
    "reviews.offerBillingTransfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferReviewBillingTransferRequest"];
            };
        };
        responses: {
            /** @description ReviewBillingTransferState */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewBillingTransferState"];
                };
            };
            /** @description capy/Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Unauthorized"];
                };
            };
            /** @description capy/Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Forbidden"];
                };
            };
            /** @description capy/ReviewRefused */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_ReviewRefused"];
                };
            };
        };
    };
    "reviews.acceptBillingTransfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewBillingTransferRequest"];
            };
        };
        responses: {
            /** @description ReviewBillingTransferState */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewBillingTransferState"];
                };
            };
            /** @description capy/Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Unauthorized"];
                };
            };
            /** @description capy/Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Forbidden"];
                };
            };
            /** @description capy/ReviewRefused */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_ReviewRefused"];
                };
            };
        };
    };
    "reviews.cancelBillingTransfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewBillingTransferRequest"];
            };
        };
        responses: {
            /** @description ReviewBillingTransferState */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewBillingTransferState"];
                };
            };
            /** @description capy/Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Unauthorized"];
                };
            };
            /** @description capy/Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Forbidden"];
                };
            };
            /** @description capy/ReviewRefused */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_ReviewRefused"];
                };
            };
        };
    };
    "reviews.declineBillingTransfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewBillingTransferRequest"];
            };
        };
        responses: {
            /** @description ReviewBillingTransferState */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewBillingTransferState"];
                };
            };
            /** @description capy/Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Unauthorized"];
                };
            };
            /** @description capy/Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Forbidden"];
                };
            };
            /** @description capy/ReviewRefused */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_ReviewRefused"];
                };
            };
        };
    };
    "reviews.start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartReviewRequest"];
            };
        };
        responses: {
            /** @description ReviewStarted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewStarted"];
                };
            };
            /** @description capy/Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Unauthorized"];
                };
            };
            /** @description capy/PaidFeatureUnavailable */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_PaidFeatureUnavailable"];
                };
            };
            /** @description capy/ReviewRefused */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_ReviewRefused"];
                };
            };
            /** @description capy/BillingAuthorityUnavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_BillingAuthorityUnavailable"];
                };
            };
        };
    };
    "usage.get": {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description UsageReport */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageReport"];
                };
            };
            /** @description capy/InvalidRequest */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_InvalidRequest"];
                };
            };
            /** @description capy/Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["capy_Unauthorized"];
                };
            };
        };
    };
}
